# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-07 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20181128_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=120),
        ),
    ]
