# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-07 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181207_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_for', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('m&f', 'Male & Female'), ('baby', 'Baby')], max_length=120, null=True)),
                ('product_type', models.CharField(blank=True, max_length=180, null=True)),
                ('material', models.CharField(blank=True, max_length=180, null=True)),
                ('product_size', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.Product')),
            ],
        ),
    ]
