# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 07:34
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181211_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=imagekit.models.fields.ProcessedImageField(upload_to=products.models.upload_img_path),
        ),
    ]
