# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181212_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
